http:
  middlewares:
    corsHeader:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlAllowHeaders: "Content-Type, Authorization, X-Requested-With"
        accessControlAllowOriginList:
          - "http://web.domain.tld"
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true

    rateLimit:
      rateLimit:
        average: 100
        period: 1m
        burst: 30
