http:
  routers:
    # API → Go-сервис
    jigsaw-api:
      rule: "Host(`jigsaw.domain.tld`) && PathPrefix(`/api`)"
      entrypoints:
        - web
      service: jigsaw-api
      middlewares:
        - corsHeader
        - rateLimit

    # Всё остальное → статика фронтенда
    jigsaw-web:
      rule: "Host(`jigsaw.domain.tld`)"
      entrypoints:
        - web
      service: jigsaw-web
      priority: 1

  services:
    jigsaw-api:
      loadBalancer:
        servers:
          - url: "http://jigsaw:8082"

    jigsaw-web:
      loadBalancer:
        servers:
          - url: "http://jigsaw-web:3000"

  middlewares:
    corsHeader:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlAllowHeaders: "Content-Type, Authorization, X-Requested-With"
        accessControlAllowOriginList:
          - http://jigsaw.domain.tld
        accessControlAllowCredentials: true
        accessControlMaxAge: 100
        addVaryHeader: true
    rateLimit:
      rateLimit:
        average: 100
        period: 1m
        burst: 30
