services:
  jigsaw:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: jigsaw
    ports:
      - "8090:8080"
    environment:
      - PORT=8080
      - DB_DSN=postgres://dev:dev@postgres:5432/jigsaw?sslmode=disable
      - LOG_LEVEL=info
      - LOG_FMT=console
      - S3_ENDPOINT=http://seaweedfs:8333
      - S3_ACCESS_KEY=any
      - S3_SECRET_KEY=any
      - S3_BUCKET_NAME=jigsaw
      - S3_REGION=us-east-1
    depends_on:
      postgres:
        condition: service_healthy
      seaweedfs:
        condition: service_started
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jigsaw-api.rule=Host(`web.domain.tld`) && PathPrefix(`/api`)"
      - "traefik.http.routers.jigsaw-api.entrypoints=web"
      - "traefik.http.routers.jigsaw-api.priority=10"
      - "traefik.http.routers.jigsaw-api.middlewares=corsHeader@file"
      - "traefik.http.services.jigsaw-api.loadbalancer.server.port=8080"

  jigsaw-web:
    image: nginx:alpine
    container_name: jigsaw-web
    volumes:
      - ../web/dist:/usr/share/nginx/html:ro
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - jigsaw
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jigsaw-web.rule=Host(`web.domain.tld`)"
      - "traefik.http.routers.jigsaw-web.entrypoints=web"
      - "traefik.http.routers.jigsaw-web.priority=1"
      - "traefik.http.services.jigsaw-web.loadbalancer.server.port=80"
